---
- hosts: playground
  remote_user: root
  gather_facts: no
  vars_files:
    - ../vars/project_vars.yml
  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: install packages
      apt:
        name: [
          'ufw', 'python3-pip', 'python3-dev', 'python3-psycopg2',
          'libpq-dev', 'build-essential', 'postgresql', 'postgresql-contrib',
          'nginx', 'curl', 'git']
        state: present

    - name: create group deployers
      group:
        name: deployers
        state: present

    - name: allow 'deployers' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%deployers'
        line: '%deployers ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: create deploy user
      user:
        name: "{{ deploy_user_name }}"
        groups: deployers
        append: yes
        state: present

    - name: Set up authorized keys for the deployer user
      authorized_key:
        user: "{{ deploy_user_name }}"
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        state: present
        exclusive: yes

    - name: ufw allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: enable ufw
      ufw:
        state: enabled
        policy: allow

    - name: ufw allow Nginx
      ufw:
        rule: allow
        name: Nginx Full

