---
- hosts: playground
  remote_user: root
  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: create group deployers
      group:
        name: deployers
        state: present

    - name: allow 'deployers' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%deployers'
        line: '%deployers ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: create django_user
      user:
        name: django_user
        groups: deployers
        append: yes
        state: present

    - name: Set up authorized keys for the deployer user
      authorized_key:
        user: django_user
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        state: present
        exclusive: yes

    - name: install ufw
      apt:
        name: ufw
        state: present

    - name: ufw allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: enable ufw
      ufw:
        state: enabled
        policy: allow

    - name: install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: install python3-dev
      apt:
        name: python3-dev
        state: present

    - name: install libpq-dev
      apt:
        name: libpq-dev
        state: present

    - name: install postgresql
      apt:
        name: postgresql
        state: present

    - name: install postgresql-contrib
      apt:
        name: postgresql-contrib
        state: present

    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: ufw allow Nginx
      ufw:
        rule: allow
        name: Nginx Full

    - name: install curl
      apt:
        name: curl
        state: present
